export const GAMING = [

    {
        id: 1,
        model: 'Nitro 5 Gaming Laptop - AN515-45-R00V',
        modelBrand: 'ACER',
        image: 'https://images.acer.com/is/image/acer/Nitro5_AN51555_WP_RGBKBUK_1_Bl-1?$Product-Cards-XL$', 
        cpu: 'AMD Ryzen™ 5 5600H',
        cpuBrand: 'AMD',
        gpu: 'NVIDIA® GeForce® GTX 1650',
        gpuBrand: 'NVIDIA',
        display: '15.6" Full HD (1920 x 1080) 16:9 144 Hz',
        displayInch: '15.6',
        ram: '8 GB',
        ramType: 'DDR4',
        storage: '256 GB SSD',
        price: 749.99,
        quantity : 0,
        itemClass: 'gaming'
    },

    {
        id: 2,
        model: 'Victus 15z-fb000',
        modelBrand: 'HP',
        image: 'https://uelectronica.com/wp-content/uploads/2022/10/hp-victus.jpg', 
        cpu: 'AMD Ryzen™ 5 5600H',
        cpuBrand: 'AMD',
        gpu: 'NVIDIA® GeForce® GTX 1650',
        gpuBrand: 'NVIDIA',
        display: '15.6" diagonal, FHD (1920 x 1080)',
        displayInch: '15.6',
        ram: '8 GB',
        ramType: 'DDR4',
        storage: '256 GB SSD',
        price: 679.99,
        quantity : 0,
        itemClass: 'gaming'
    },

    {
        id: 3,
        model: 'IdeaPad Gaming 3',
        modelBrand: 'LENOVO',
        image: 'https://braincorp.com.ve/wp-content/uploads/2022/09/6500619_sd-scaled.webp', 
        cpu: 'AMD Ryzen™ 7 5800H',
        cpuBrand: 'AMD',
        gpu: 'NVIDIA® GeForce® RTX™ 3050',
        gpuBrand: 'NVIDIA',
        display: '15.6" FHD (1920 x 1080) 120 Hz',
        displayInch: '15.6',
        ram: '8 GB',
        ramType: 'DDR4',
        storage: '256 GB SSD',
        price: 679.99,
        quantity : 0,
        itemClass: 'gaming'
    },

    {
        id: 4,
        model: 'Predator Triton 300 PT315-53-70L0',
        modelBrand: 'ACER',
        image: 'https://images.acer.com/is/image/acer/Triton-300-PT315-53-Backliton-Black-01a-1', 
        cpu: 'Intel® Core™ i7-11800H',
        cpuBrand: 'INTEL',
        gpu: 'NVIDIA® GeForce RTX™ 3070',
        gpuBrand: 'NVIDIA',
        display: '15.6" (1920 x 1080) 144 Hz',
        displayInch: '15.6',
        ram: '16 GB',
        ramType: 'DDR4',
        storage: '512 GB SSD',
        price: 1199.99,
        quantity : 0,
        itemClass: 'gaming'
    },

    {
        id: 5,
        model: 'ROG Zephyrus G15 GA503',
        modelBrand: 'ASUS',
        image: 'https://i.blogs.es/280903/ga503_rog_zephyrus_g15_moonlightwhite_01/original.jpeg', 
        cpu: 'AMD R9-5900HS',
        cpuBrand: 'AMD',
        gpu: 'NVIDIA® GeForce RTX 3060',
        gpuBrand: 'NVIDIA',
        display: '15.6" (2560 x 1440) 144 Hz',
        displayInch: '15.6',
        ram: '16 GB',
        ramType: 'DDR4',
        storage: '512 GB SSD',
        price: 1489.99,
        quantity : 0,
        itemClass: 'gaming'
    },

    {
        id: 6,
        model: 'Alienware 51m R2',
        modelBrand: 'ALIENWARE',
        image: 'https://m.media-amazon.com/images/I/41c0UMkTrtS.jpg', 
        cpu: 'Intel® Core™ i7-10700K',
        cpuBrand: 'INTEL',
        gpu: 'NVIDIA® GeForce RTX 2070 Super',
        gpuBrand: 'NVIDIA',
        display: '17.3" (1920x1080) 144 Hz',
        displayInch: '17.3',
        ram: '32 GB',
        ramType: 'DDR4',
        storage: '1000 GB SSD',
        price: 1899.99,
        quantity : 0,
        itemClass: 'gaming'
    },

    {
        id: 7,
        model: 'MSI Katana GF76',
        modelBrand: 'MSI',
        image: 'https://www.lobaratosalecaro.com/wp-content/uploads/2022/06/MSI-Katana-GF76-12UE-058XES-opiniones-e1654767799722.jpg', 
        cpu: 'Intel® Core™ i7-12700H',
        cpuBrand: 'INTEL',
        gpu: 'NVIDIA® GeForce RTX 3060',
        gpuBrand: 'NVIDIA',
        display: '17.3" (1920x1080) 144 Hz',
        displayInch: '17.3',
        ram: '16 GB',
        ramType: 'DDR4',
        storage: '512 GB SSD',
        price: 1299.99,
        quantity : 0,
        itemClass: 'gaming'
    }
]

export const CHROMEBOOKS = [

    {
        id: 8,
        model: 'Acer Chromebook Spin 714',
        modelBrand: 'ACER',
        image: 'https://images.acer.com/is/image/acer/acer-chromebook-enterprise-spin-714-cp714-1wn-antimicrobial-with-fingerprint-backlit-on-wallpaper-chrome-ui-steel-gray-01-2?$Product-Cards-XL$', 
        cpu: 'Intel® Core™ i5-1235U',
        cpuBrand: 'INTEL',
        gpu: 'Intel® Iris® Xe Graphics',
        gpuBrand: 'INTEL',
        display: '14" WUXGA (1920 x 1200)',
        displayInch: '14',
        ram: '16 GB',
        ramType: 'DDR4',
        storage: '256 GB SSD',
        price: 949.99,
        quantity : 0,
        itemClass: 'chromebook'
    },

    {
        id: 9,
        model: 'IdeaPad Flex 5i Gen 7',
        modelBrand: 'LENOVO',
        image: 'https://www.lenovo.com/medias/download.png?context=bWFzdGVyfHJvb3R8ODQ1MDI0fGltYWdlL3BuZ3xoMDgvaDI1LzE0NDA4MDEyMDM4MTc0LnBuZ3wzYTZlNDczZGJmZThmOGFkZjA1NTYxNTVlZTc3NDYwMDAzNjE5ZTJkNTk1YmI0ZGNkNWVhNzkzN2YzNmQxZmI4', 
        cpu: 'Intel® Core™ i7-1255U',
        cpuBrand: 'INTEL',
        gpu: 'Intel® Iris® Xe Graphics',
        gpuBrand: 'INTEL',
        display: '14" WUXGA (1920 x 1200) 60Hz',
        displayInch: '14',
        ram: '16 GB',
        ramType: 'DDR4',
        storage: '256 GB SSD',
        price: 829.99,
        quantity : 0,
        itemClass: 'chromebook'
    },

    {
        id: 10,
        model: 'HP Chromebook x360',
        modelBrand: 'HP',
        image: 'https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c06526009.png', 
        cpu: 'Intel® Core™ Celeron N4020',
        cpuBrand: 'INTEL',
        gpu: 'Intel® UHD 600 Graphics',
        gpuBrand: 'INTEL',
        display: '12.7" FHD (1366 x 768)',
        displayInch: '12.7',
        ram: '4 GB',
        ramType: 'DDR4',
        storage: '32 GB eMMC',
        price: 219.99,
        quantity : 0,
        itemClass: 'chromebook'
    },

    {
        id: 11,
        model: 'Samsung Galaxy Chromebook 2',
        modelBrand: 'SAMSUNG',
        image: 'https://d1b5h9psu9yexj.cloudfront.net/45821/Samsung-Galaxy-Chromebook-2_20210714-210157_full.png', 
        cpu: 'Intel® Core™ i3-10110U',
        cpuBrand: 'INTEL',
        gpu: 'Intel® Iris® Xe Graphics',
        gpuBrand: 'INTEL',
        display: '13.3" (1920 x 1080)',
        displayInch: '13.3',
        ram: '8 GB',
        ramType: 'DDR4',
        storage: '128 GB eMMC',
        price: 699.99,
        quantity : 0,
        itemClass: 'chromebook'
    },

    {
        id: 12,
        model: 'Asus Chromebook Flip C536',
        modelBrand: 'ASUS',
        image: 'https://d1b5h9psu9yexj.cloudfront.net/48370/Asus-Chromebook-Flip-C536--C536EA-BI3T3-_20211119-221342_full.jpg', 
        cpu: 'Intel® Core™ i3-1115G4',
        cpuBrand: 'AMD',
        gpu: 'Intel® Iris® Xe Graphics',
        gpuBrand: 'INTEL',
        display: '15.6" (1920 x 1080)',
        displayInch: '15.6',
        ram: '16 GB',
        ramType: 'DDR4',
        storage: '128 GB SSD',
        price: 379.99,
        quantity : 0,
        itemClass: 'chromebook'
    },

    {
        id: 13,
        model: 'Acer Chromebook 516 GE',
        modelBrand: 'ACER',
        image: 'https://images.acer.com/is/image/acer/acer-chormebook-516-ge-cbg516-1h-backlit-on-color-wallpaper-chrome-ui-1-titanium-gray-01-1?$Product-Cards-XL$', 
        cpu: 'Intel® Core™ i7-1260P',
        cpuBrand: 'INTEL',
        gpu: 'Intel® Iris® Xe Graphics',
        gpuBrand: 'INTEL',
        display: '16" (2560 x 1600) 120 Hz',
        displayInch: '16',
        ram: '16 GB',
        ramType: 'DDR4',
        storage: '256 GB SSD',
        price: 649.99,
        quantity : 0,
        itemClass: 'chromebook'
    },

    {
        id: 14,
        model: 'Lenovo IdeaPad Duet 5',
        modelBrand: 'LENOVO',
        image: 'https://p4-ofp.static.pub/fes/cms/2022/08/17/9xc3n5wtk6e90yuz1kbwmowbmsqxlo996774.png', 
        cpu: 'Qualcomm Snapdragon 7 Gen. 2',
        cpuBrand: 'QUALCOMM',
        gpu: 'Qualcomm Adreno 618',
        gpuBrand: 'QUALCOMM',
        display: '13.3" (1920x1080) 144 Hz',
        displayInch: '13.3',
        ram: '8 GB',
        ramType: 'DDR4',
        storage: '256 GB eMMC',
        price: 409.99,
        quantity : 0,
        itemClass: 'chromebook'
    }
]

export const BUSINESS = [

    {
        id: 15,
        model: 'Lenovo ThinkPad X1 Carbon Gen 10',
        modelBrand: 'LENOVO',
        image: 'https://i5.walmartimages.com/asr/efd2fbf6-79d9-4ad7-b5bf-7faa4392574e.0f18c5319202b03044706c516d5e0c4b.jpeg', 
        cpu: 'Intel® Core™ i7 vPro',
        cpuBrand: 'INTEL',
        gpu: 'Intel® Iris® Xe Graphics',
        gpuBrand: 'INTEL',
        display: '14" Full HD (3840 x 2400)',
        displayInch: '14',
        ram: '32 GB',
        ramType: 'DDR5',
        storage: '2000 GB SSD',
        price: 1399.99,
        quantity : 0,
        itemClass: 'business'
    },

    {
        id: 16,
        model: 'Apple MacBook Pro 13',
        modelBrand: 'APPLE',
        image: 'https://m.media-amazon.com/images/I/313CFbI-YjL._AC_SY1000_.jpg', 
        cpu: 'Apple M2 Chip',
        cpuBrand: 'APPLE',
        gpu: 'Apple M2 Graphics',
        gpuBrand: 'APPLE',
        display: '13.3" LED IPS (2560 x 1600)',
        displayInch: '13.3',
        ram: '16 GB',
        ramType: 'DDR4',
        storage: '512 GB SSD',
        price: 1099.99,
        quantity : 0,
        itemClass: 'business'
    },

    {
        id: 17,
        model: 'Lenovo ThinkPad P1 Gen 4',
        modelBrand: 'LENOVO',
        image: 'https://p1-ofp.static.pub/medias/bWFzdGVyfHJvb3R8NzU2MDN8aW1hZ2UvcG5nfGhmNS9oODcvMTE2NTY4NDIxODI2ODYucG5nfGFmMDU2ZTJlYjY0MDA3ZDRhMTY3MDM0ODY1OTM4OWE1OWViMmZkNTIyY2JlZjgzZjVhNzE1MTNkZDNhZmMyYjM/lenovo-laptops-think-thinkpad-p-series-p1-gen4-16inch-intel-gallery-5.png', 
        cpu: 'Intel® Core™ i7-11800H',
        cpuBrand: 'INTEL',
        gpu: 'NVIDIA RTX™ A2000',
        gpuBrand: 'NVIDIA',
        display: '16" WQXGA (2560 x 1600)',
        displayInch: '16',
        ram: '16 GB',
        ramType: 'DDR4',
        storage: '1000 GB SSD',
        price: 1149.99,
        quantity : 0,
        itemClass: 'business'
    },

    {
        id: 18,
        model: 'Lenovo ThinkPad Z13',
        modelBrand: 'LENOVO',
        image: 'https://www.notebookcheck.org/fileadmin/_processed_/e/5/csm_ThinkPad_Z13_Black_01_9f035c50c1.png', 
        cpu: 'AMD Ryzen™ PRO 6000 U',
        cpuBrand: 'AMD',
        gpu: 'AMD RDNA™-2',
        gpuBrand: 'AMD',
        display: '13.3" WQXGA (2880 x 1800)',
        displayInch: '13.3',
        ram: '32 GB',
        ramType: 'DDR5',
        storage: '1000 GB SSD',
        price: 1299.99,
        quantity : 0,
        itemClass: 'business'
    },

    {
        id: 19,
        model: 'HP EliteBook 840 G9',
        modelBrand: 'HP',
        image: 'https://phnx-tmp-upload.s3.us-west-2.amazonaws.com/l1WiWsMekCwgnWciu0ixq6wRKousaxkWB9dVBTkn.jpg', 
        cpu: 'Intel® Core™ i5-1135G7',
        cpuBrand: 'INTEL',
        gpu: 'Intel® Iris® Xe Graphics',
        gpuBrand: 'INTEL',
        display: '14" 1080p (1920 x 1200)',
        displayInch: '14',
        ram: '8 GB',
        ramType: 'DDR5',
        storage: '512 GB SSD',
        price: 379.99,
        quantity : 0,
        itemClass: 'business'
    },

    {
        id: 20,
        model: 'Dell Latitude 5430',
        modelBrand: 'DELL',
        image: 'https://phnx-tmp-upload.s3.us-west-2.amazonaws.com/XsEAzecCXhfJCYfMRn1RFWovAX1kChyFFEmZzvHR.jpg', 
        cpu: 'Intel® Core™ i5-1235U',
        cpuBrand: 'INTEL',
        gpu: 'Intel® Iris® Xe Graphics',
        gpuBrand: 'INTEL',
        display: '14" FHD 1080p (1920 x 1080)',
        displayInch: '14',
        ram: '16 GB',
        ramType: 'DDR4',
        storage: '256 GB SSD',
        price: 689.99,
        quantity : 0,
        itemClass: 'business'
    },

    {
        id: 21,
        model: 'HP Spectre x360',
        modelBrand: 'HP',
        image: 'https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08184647.png', 
        cpu: 'Intel® Core i7-1165G7',
        cpuBrand: 'INTEL',
        gpu: 'Intel® Iris® Xe Graphics',
        gpuBrand: 'INTEL',
        display: '14" FHD (1920 x 1280)',
        displayInch: '14',
        ram: '8 GB',
        ramType: 'DDR4',
        storage: '256 GB SSD',
        price: 749.99,
        quantity : 0,
        itemClass: 'business'
    }
]

